# Base general: Informacion de ingresos y egresos hospitalarios 
En este notebook se visualizan los datos de ingresos y egresos hospitalarios de Salud
Se utilizan datos de 2015 a 2024, y se visualizan los flujos de pacientes entre provincias, asi como las causas mas comunes de ingreso hospitalario.

In [33]:
import polars as pl
import gc

In [34]:
base_general=pl.read_csv("../../data/data_hospitales/sistema_salud_egresos.csv",infer_schema=0)

In [35]:
base_general.schema

Schema([('prov_ubi', String),
        ('cant_ubi', String),
        ('parr_ubi', String),
        ('area_ubi', String),
        ('clase', String),
        ('tipo', String),
        ('entidad', String),
        ('sector', String),
        ('mes_inv', String),
        ('nac_pac', String),
        ('nom_pais', String),
        ('cod_pais', String),
        ('sexo', String),
        ('cod_edad', String),
        ('edad', String),
        ('etnia', String),
        ('prov_res', String),
        ('cant_res', String),
        ('parr_res', String),
        ('area_res', String),
        ('anio_ingr', String),
        ('mes_ingr', String),
        ('dia_ingr', String),
        ('fecha_ingr', String),
        ('anio_egr', String),
        ('mes_egr', String),
        ('dia_egr', String),
        ('fecha_egr', String),
        ('dia_estad', String),
        ('con_egrpa', String),
        ('esp_egrpa', String),
        ('cau_cie10', String),
        ('causa3', String),
        ('cap221rx', String),
        ('cau221rx', String),
        ('cau298rx', String),
        ('archivo_origen', String),
        ('tipo_seg', String),
        ('dis_pac', String)])

In [36]:
base_general.describe()

shape: (9, 40)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ prov_ubi  ┆ cant_ubi ┆ parr_ubi  ┆ … ┆ cau298rx  ┆ archivo_o ┆ tipo_seg  ┆ dis_pac   │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ rigen     ┆ ---       ┆ ---       │
│ str       ┆ str       ┆ str      ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 11172616  ┆ 11172616 ┆ 11172616  ┆ … ┆ 11172616  ┆ 11172616  ┆ 1132667   ┆ 1132667   │
│ null_coun ┆ 0         ┆ 0        ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 10039949  ┆ 10039949  │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ std       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min       ┆ AZUAY     ┆ AGUARICO ┆ 10 DE     ┆ … ┆ 10 Brucel ┆ egresos_h ┆ IESS,     ┆ Discapaci │
│           ┆           ┆          ┆ NOVIEMBRE ┆   ┆ osis      ┆ ospitalar ┆ afiliado  ┆ dad       │
│           ┆           ┆          ┆           ┆   ┆           ┆ ios_2015. ┆ seguro    ┆ auditiva  │
│           ┆           ┆          ┆           ┆   ┆           ┆ csv       ┆ campesin… ┆           │
│ 25%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max       ┆ ZAMORA    ┆ ZARUMA   ┆ ZUMBAHUA  ┆ … ┆ Úlcera    ┆ egresos_h ┆ Sin infor ┆ Sin infor │
│           ┆ CHINCHIPE ┆          ┆           ┆   ┆ gástrica  ┆ ospitalar ┆ mación    ┆ mación    │
│           ┆           ┆          ┆           ┆   ┆ y         ┆ ios_2024. ┆           ┆           │
│           ┆           ┆          ┆           ┆   ┆ duodenal  ┆ csv       ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [37]:
identificadores = [
    'clase',
    'tipo',
    'entidad',
    'sector'
]
territorio_ubi=[    
    'prov_ubi',
    'cant_ubi',
    'parr_ubi',
    #'area_ubi',

]
territorio_res = [
    'prov_res',
    'cant_res',
    'parr_res',
    #'area_res',
]

fecha_egr = [
    'fecha_egr',

]

estadisticas = [
    'dia_estad', #dias de estadia
    'con_egrpa', # egreso vivo o muerto (antes o despues de 48 horas)
]

diagnostico=[
    "cau_cie10",
    "causa3",
    "cap221rx",
    "cau221rx",
    "cau298rx",
]

demografia=[
    "sector",
    "mes_inv",
    "nac_pac",
    "nom_pais",
    "cod_pais",
    "sexo",
    "cod_edad",
    "edad",
    "etnia",
    
]

In [38]:
base_general["cod_edad"].value_counts(sort=True)

shape: (4, 2)
┌──────────────────────────────┬──────────┐
│ cod_edad                     ┆ count    │
│ ---                          ┆ ---      │
│ str                          ┆ u32      │
╞══════════════════════════════╪══════════╡
│ Años (1 a 115 años de edad)  ┆ 10456723 │
│ Horas (1 a 23 horas de edad) ┆ 257903   │
│ Meses (1 a 11 meses de edad) ┆ 231523   │
│ Días (1 a 28 días de edad)   ┆ 226467   │
└──────────────────────────────┴──────────┘

In [39]:
# Obtener los value_counts de 'col1' agrupados por 'col2'
result = base_general.group_by("cod_edad").agg([
    pl.col("edad").value_counts().alias("edad_counts")
])

print(result)

shape: (4, 2)
┌──────────────────────────────┬─────────────────────────────────┐
│ cod_edad                     ┆ edad_counts                     │
│ ---                          ┆ ---                             │
│ str                          ┆ list[struct[2]]                 │
╞══════════════════════════════╪═════════════════════════════════╡
│ Horas (1 a 23 horas de edad) ┆ [{"1.0",199554}, {"7.0",2252},… │
│ Días (1 a 28 días de edad)   ┆ [{"1.0",102672}, {"5.0",7835},… │
│ Años (1 a 115 años de edad)  ┆ [{"66.0",89698}, {"26.0",23896… │
│ Meses (1 a 11 meses de edad) ┆ [{"4.0",18383}, {"8.0",20900},… │
└──────────────────────────────┴─────────────────────────────────┘

In [40]:
# Función para mapear las edades
def map_edad_to_years(cod_edad, edad):
    if cod_edad == "Horas (1 a 23 horas de edad)":
        return float(edad) / 24 / 365  # Convertir horas a años
    elif cod_edad == "Días (1 a 28 días de edad)":
        return float(edad) / 365  # Convertir días a años
    elif cod_edad == "Meses (1 a 11 meses de edad)":
        return float(edad) / 12  # Convertir meses a años
    elif cod_edad == "Años":
        return float(edad)  # Ya está en años
    return float(edad)

# Crear una nueva columna con la edad estandarizada

# # Función de mapeo

# def map_if_has_code(cau_value,cie_code):
#     return mapping_with_code.get((cau_value, cie_code), cie_code)

# Aplicar el mapeo utilizando map_batches
base_general = base_general.with_columns(
    pl.struct(["cod_edad", "edad"])  # Crear un struct de las dos columnas
    .map_elements(  # Aplicar la función en batches
        lambda batch: map_edad_to_years(
            batch.get("cod_edad"),
            batch.get("edad"),
            ),  # Aplicar la función
        return_dtype=pl.Float64,  # El tipo de dato de retorno es cadena
    ).alias("edad_std")  # Asignar la nueva columna
)

In [41]:
columns_to_extract = (identificadores+territorio_ubi + territorio_res + fecha_egr + estadisticas + diagnostico+["edad_std"])
#base_general_filtrada=base_general.select(columns_to_extract)
base_general_filtrada=base_general.clone()
del base_general
gc.collect()

0

In [42]:

edades=base_general_filtrada["edad_std"].value_counts(sort=True)

#### Mapeo cau221rx

In [43]:
# leer diccionario del archivo: notebooks/limpieza/nuevo_diccionario_cau221rx.txt
import ast

# 1. Leemos el contenido del archivo .txt
with open("nuevo_diccionario_cau221rx.txt", "r", encoding="utf-8") as f:
    contenido = f.read()

# 2. Limpiamos el texto para quedarnos solo con lo que está después del '='
# Esto elimina "dictionary = " y nos deja solo con el "{...}"
if "=" in contenido:
    str_diccionario = contenido.split("=", 1)[1].strip()
else:
    str_diccionario = contenido.strip()

# 3. Lo convertimos en un objeto diccionario real
nuevo_diccionario = ast.literal_eval(str_diccionario)

# Ahora ya puedes usarlo normalmente
print(type(nuevo_diccionario))
print(nuevo_diccionario["129 Artropatías infecciosas (M00-M03)"])

<class 'dict'>
Artropatías infecciosas (M00-M03)

In [44]:

base_general_filtrada=base_general_filtrada.with_columns(
    pl.col("cau221rx")
    .replace(nuevo_diccionario, default=None)
    .alias("cau221rx_std")
)

C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\921888413.py:3: DeprecationWarning: the `default` parameter for `replace` is deprecated. Use `replace_strict` instead to set a default while replacing values.
(Deprecated in version 1.0.0)
  .replace(nuevo_diccionario, default=None)

In [45]:
base_general_filtrada["cau221rx_std"].value_counts()

shape: (223, 2)
┌─────────────────────────────────┬────────┐
│ cau221rx_std                    ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Enfermedades del oído medio y … ┆ 10642  │
│ Esquizofrenia, trastornos esqu… ┆ 15050  │
│ Edema, proteinuria, y trastorn… ┆ 128999 │
│ Malformaciones congénitas del … ┆ 5553   │
│ Síntomas y signos que involucr… ┆ 8062   │
│ …                               ┆ …      │
│ Trastornos del humor [afectivo… ┆ 25924  │
│ Tumor maligno de la mama (C50)  ┆ 45380  │
│ Trastornos papuloescamosos (L4… ┆ 1536   │
│ Hallazgos anormales en el exam… ┆ 50     │
│ Hernia (K40-K46)                ┆ 244247 │
└─────────────────────────────────┴────────┘

In [46]:
base_general_filtrada.select(pl.col("cau221rx_std").is_null().sum())

shape: (1, 1)
┌──────────────┐
│ cau221rx_std │
│ ---          │
│ u32          │
╞══════════════╡
│ 0            │
└──────────────┘

In [47]:
# see wich cau221rx doesnt have a match in cau221rx_dict
cau221rx_not_maped=base_general_filtrada.filter(base_general_filtrada["cau221rx_std"].is_null())

In [48]:
cau221rx_review = (
    base_general_filtrada
    .group_by("cau221rx") # Agrupamos por el código
    .len()                     # Contamos (en versiones viejas usa .count())
    .sort("len", descending=True) # Ordenamos de mayor a menor
)

display(cau221rx_review)

shape: (474, 2)
┌─────────────────────────────────┬────────┐
│ cau221rx                        ┆ len    │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Parto (O80-O84)                 ┆ 692465 │
│ 160 Parto (O80-O84)             ┆ 621518 │
│ 119 Trastornos de la vesícula … ┆ 303910 │
│ Trastornos de la vesícula bili… ┆ 271842 │
│ Atención materna relacionada c… ┆ 217029 │
│ …                               ┆ …      │
│ Otras enfermedades causadas po… ┆ 19     │
│ 7 Otras enfermedades causadas … ┆ 9      │
│ 194 Hallazgos anormales en el … ┆ 9      │
│ null                            ┆ 4      │
│ Síntomas y signos que involucr… ┆ 2      │
└─────────────────────────────────┴────────┘

## Mapeo cie10

##### Intento en polars

In [49]:
# import re
# import pandas as pd
# from rapidfuzz import fuzz, process


# def build_canonical_mapping(values, similarity_threshold=90):
#     uniques = sorted(set(values))
#     mapping = {}   # old -> canonical
#     seen = set()   # already assigned to some cluster

#     for val in uniques:
#         if val in seen:
#             continue

#         # Find similar strings
#         matches = process.extract(
#             val,
#             uniques,
#             scorer=fuzz.token_sort_ratio,
#             score_cutoff=similarity_threshold
#         )

#         group_vals = {v for v, score, idx in matches}
#         group_vals.add(val)

#         # choose the "most informative" one — here, longest string
#         canonical_val = max(group_vals, key=len)

#         for v in group_vals:
#             mapping[v] = canonical_val
#             seen.add(v)

#     return mapping

# # Extracción de código CIE
# def extract_cie_code(text):
#     if text is None:
#         return None
#     text = str(text)
#     m = re.search(r'\b([A-Z]\d{2,3}[A-Z0-9]?)\b', text)
#     return m.group(1) if m else ""

    
# def map_no_code_row(row):
#     if row["cie_code"] is not None:
#         return row["cau_cie10_temp"]
    
#     cau = row["cau221rx_std"]
#     text = str(row["cau_cie10"])
    
#     if cau not in candidates_by_cau:
#         return row["cau_cie10_temp"]
    
#     candidates = list(candidates_by_cau[cau])
    
#     # Buscar el candidato más similar
#     match, score, _ = process.extractOne(
#         text, candidates, scorer=fuzz.token_sort_ratio
#     )
    
#     if score >= SIM_THRESHOLD:
#         return match
#     else:
#         return row["cau_cie10_temp"]

In [50]:

# # DataFrame original en Polars
# base_genera_cie = base_general_filtrada[["cau221rx_std", "cau_cie10"]].unique(maintain_order=True)

# # Agregar el código CIE
# base_genera_cie = base_genera_cie.with_columns(
#     pl.col("cau_cie10").map_elements(extract_cie_code,return_dtype=pl.Utf8).alias("cie_code")
# )
# # Crear el mapeo con códigos
# mapping_with_code = {}

# # Filtrar las filas que contienen códigos
# df_with_code = base_genera_cie.filter(pl.col("cie_code").is_not_null())
# df_no_grouped=df_with_code.clone()

# # Cambia esta línea:
# # for cau_value, cie_code in df_with_code.group_by(["cau221rx_std", "cie_code"]):

# # Por esta:
# for group in df_with_code.group_by(["cau221rx_std", "cie_code"]):
#     # Desempaquetar el grupo
#     (cau_value, cie_code), subdf = group
    
#     # Obtener los valores únicos de cau_cie10
#     values = subdf["cau_cie10"].unique()
    
#     if len(values) == 0:
#         continue
    
#     # Regla: el texto más largo es el más informativo
#     canonical = max(values, key=len)
    
#     for v in values:
#         mapping_with_code[(cau_value, v)] = canonical

In [51]:


# # Función de mapeo

# def map_if_has_code(cau_value,cie_code):
#     return mapping_with_code.get((cau_value, cie_code), cie_code)

# # Aplicar el mapeo utilizando map_batches
# base_genera_cie = base_genera_cie.with_columns(
#     pl.struct(["cau221rx_std", "cau_cie10"])  # Crear un struct de las dos columnas
#     .map_elements(  # Aplicar la función en batches
#         lambda batch: map_if_has_code(
#             batch.get("cau221rx_std"),
#             batch.get("cau_cie10"),
#             ),  # Aplicar la función
#         return_dtype=pl.Utf8,  # El tipo de dato de retorno es cadena
#     ).alias("cau_cie10_temp")  # Asignar la nueva columna
# )

In [52]:
# # Asegúrate de usar map_elements y NO map_batches
# base_genera_cie = base_genera_cie.with_columns(
#     pl.struct(["cau221rx_std", "cau_cie10"])
#     .map_elements(
#         lambda x: mapping_with_code.get((x["cau221rx_std"], x["cau_cie10"]), x["cau_cie10"]),
#         return_dtype=pl.String
#     )
#     .alias("cau_cie10_temp")
# )

In [53]:

# # Función de mapeo
# def map_if_has_code(struct):
#     cau_value = struct.field("cau221rx_std")  # Extraer el valor de cau221rx_std
#     cie_code = struct.field("cau_cie10")        # Extraer el valor de cau_cie10
#     return mapping_with_code.get((cau_value, cie_code), cie_code)

# # Aplicar el mapeo utilizando map_batches
# base_genera_cie = base_genera_cie.with_columns(
#     pl.struct(["cau221rx_std", "cau_cie10"])  # Crear un struct de las dos columnas
#     .map_batches(  # Aplicar la función en batches
#         lambda batch: batch.apply(lambda struct: map_if_has_code(struct)),  # Aplicar la función
#         return_dtype=pl.Utf8  # El tipo de dato de retorno es cadena
#     ).alias("cau_cie10_temp")  # Asignar la nueva columna
# )

In [54]:

# SIM_THRESHOLD = 90



# # Aplicar el mapeo a filas sin código
# base_genera_cie = base_genera_cie.with_columns(
#     pl.col("cau_cie10").apply(map_no_code_row).alias("cau_cie10_std")
# )

        
# # Crear el mapeo final de cau_cie10 limpio
# mapping_ciie10 = {}
# for cie_std, cie, subdf in base_genera_cie.groupby(["cau_cie10_std", "cau_cie10"]):
#     mapping_ciie10[cie] = cie_std

# # Aplicar el mapeo final a base_general_filtrada
# base_general_filtrada = base_general_filtrada.with_columns(
#     pl.col("cau_cie10").map(mapping_ciie10).alias("cau_cie10_std")
# )

##### Implementacion en Pandas

In [55]:
base_general_filtrada = base_general_filtrada.with_columns(
    pl.col("cau_cie10")
    .str.replace_all('A"', "O")  # Caso: A"RGANO -> ORGANO
    .str.replace_all('"', "O")   # Caso: SJ"GREN -> SJOGREN / WALDENSTR"M -> WALDENSTROM        # Limpieza final de espacios
)

In [56]:
base_general_filtrada_pd=base_general_filtrada.to_pandas()

In [57]:
import pandas as pd
from rapidfuzz import fuzz, process
import pandas as pd
import re

def build_canonical_mapping(values, similarity_threshold=90):
    uniques = sorted(set(values))
    mapping = {}   # old -> canonical
    seen = set()   # already assigned to some cluster

    for val in uniques:
        if val in seen:
            continue

        # Find similar strings
        matches = process.extract(
            val,
            uniques,
            scorer=fuzz.token_sort_ratio,
            score_cutoff=similarity_threshold
        )

        group_vals = {v for v, score, idx in matches}
        group_vals.add(val)

        # choose the "most informative" one — here, longest string
        canonical_val = max(group_vals, key=len)

        for v in group_vals:
            mapping[v] = canonical_val
            seen.add(v)

    return mapping

# --- 1. Configuración y Funciones Base ---
SIM_THRESHOLD = 90  # Ajusta según necesites

def extract_cie_code(text):
    if pd.isna(text):
        return None
    text = str(text)
    m = re.search(r'\b([A-Z]\d{2,3}[A-Z0-9]?)\b', text)
    return m.group(1) if m else None

def get_clean_text(text):
    """Elimina el código CIE del texto para una comparación limpia"""
    if pd.isna(text): return ""
    text = str(text)
    code = extract_cie_code(text)
    if code:
        # Reemplaza el código por nada y limpia espacios sobrantes
        return re.sub(rf'\b{re.escape(code)}\b', '', text).strip()
    return text.strip()

In [58]:
import ast
from pathlib import Path

# 1. Definimos la ruta usando Path para evitar líos con las diagonales
ruta_archivo = Path("mapping_cie10.txt")

# 2. Verificamos si el archivo existe
if ruta_archivo.exists():
    with open(ruta_archivo, "r", encoding="utf-8") as f:
        contenido = f.read()
    
    # 3. Extraemos solo la parte del diccionario (después del '=')
    if "=" in contenido:
        str_diccionario = contenido.split("=", 1)[1].strip()
    else:
        str_diccionario = contenido.strip()
    
    # 4. Intentamos convertirlo a objeto real de Python
    try:
        mapping_final_dict = ast.literal_eval(str_diccionario)
        print(f"✅ Diccionario cargado con {len(mapping_final_dict)} entradas.")

        # Ahora ya puedes usarlo normalmente
        print(type(mapping_final_dict))
        print(mapping_final_dict["T529 EFECTO TOXICO DE DISOLVENTES ORGANICOS, NO ESPECIFICADOS"])
    except (ValueError, SyntaxError) as e:
        print(f"❌ Error: El contenido del archivo no es un diccionario válido. {e}")
        mapping_final_dict = {}
else:
    
    
    print(f"⚠️ El archivo no existe en la ruta: {ruta_archivo}")

    # --- 2. Preparación de Datos ---
    # Trabajamos sobre una copia única de las combinaciones causa-texto
    base_general_filtrada_pd_ciie = base_general_filtrada_pd[["cau221rx_std", "cau_cie10"]].drop_duplicates().copy()

    # Extraer códigos y crear versiones limpias para comparar
    base_general_filtrada_pd_ciie["cie_code"] = base_general_filtrada_pd_ciie["cau_cie10"].apply(extract_cie_code)
    base_general_filtrada_pd_ciie["text_clean"] = base_general_filtrada_pd_ciie["cau_cie10"].apply(get_clean_text)

    # --- 3. Mapeo Inicial (Solo para filas que SÍ tienen código) ---
    # Esto agrupa variantes como "DIABETES A10" y "DIABETES TIPO 2 A10" bajo un mismo nombre
    mapping_with_code = {}
    df_with_code = base_general_filtrada_pd_ciie[base_general_filtrada_pd_ciie["cie_code"].notna()].copy()

    for (cau_val, cie_val), subdf in df_with_code.groupby(["cau221rx_std", "cie_code"]):
        values = subdf["cau_cie10"].dropna().unique()
        if len(values) > 0:
            canonical = max(values, key=len)
            for v in values:
                mapping_with_code[(cau_val, v)] = canonical

    # Aplicar este primer nivel de estandarización
    base_general_filtrada_pd_ciie["cau_cie10_temp"] = base_general_filtrada_pd_ciie.apply(
        lambda row: mapping_with_code.get((row["cau221rx_std"], row["cau_cie10"]), row["cau_cie10"]), 
        axis=1
    )

    # --- 4. Preparación de Candidatos para filas SIN código ---
    # Creamos un diccionario: { causa: { "texto limpio": "Texto Original Con Código" } }
    candidates_by_cau = {}
    df_candidatos = base_general_filtrada_pd_ciie[base_general_filtrada_pd_ciie["cie_code"].notna()]

    for cau, group in df_candidatos.groupby("cau221rx_std"):
        # Usamos text_clean para comparar, pero apuntamos a cau_cie10_temp (que tiene el código)
        candidates_by_cau[cau] = dict(zip(group["text_clean"], group["cau_cie10_temp"]))

    # --- 5. Función de Mapeo para Filas sin Código ---
    def map_no_code_row(row):
        # Si ya tiene código, mantenemos el valor procesado en el paso 3
        if pd.notna(row["cie_code"]):
            return row["cau_cie10_temp"]
        
        cau = row["cau221rx_std"]
        text_to_match = row["text_clean"]
        
        if cau not in candidates_by_cau or not text_to_match:
            return row["cau_cie10_temp"]
        
        choices_dict = candidates_by_cau[cau]
        choices_clean = list(choices_dict.keys())
        
        # Comparar el texto sin código contra los candidatos (también sin código)
        res = process.extractOne(
            text_to_match, 
            choices_clean, 
            scorer=fuzz.token_sort_ratio
        )
        
        if res:
            match_clean, score, idx = res
            if score >= SIM_THRESHOLD:
                # Si hay match, devolvemos la versión QUE TIENE el código
                return choices_dict[match_clean]
                
        return row["cau_cie10_temp"]

    # --- 6. Aplicación Final y Mapeo al DataFrame Original ---
    # Crear la columna limpia definitiva
    base_general_filtrada_pd_ciie["cau_cie10_std"] = base_general_filtrada_pd_ciie.apply(map_no_code_row, axis=1)

    # Crear el diccionario de mapeo final: { texto_sucio_original: texto_estandarizado_con_cie }
    mapping_final_dict = dict(zip(base_general_filtrada_pd_ciie["cau_cie10"], base_general_filtrada_pd_ciie["cau_cie10_std"]))
    del base_general_filtrada_pd
    del base_general_filtrada_pd_ciie
        #guardar el diccionario para cie10
    mapping_final_dict.update({None:"No definido"})
    # the dictiionary has to be saved in utf-8 encoding add the keys
    with open('mapping_cie10_2.txt', 'w', encoding='utf-8') as f:
        f.write("dictionary = {\n")
        for key, value in mapping_final_dict.items():
            if key is not None:
                f.write(f'\"{key}\": \"{value}\",\n')
            else: 
                f.write(f'{key}: \"{value}\",\n')
        f.write("}")

✅ Diccionario cargado con 25988 entradas.
<class 'dict'>
T529   EFECTO TOXICO DE DISOLVENTES ORGANICOS, NO ESPECIFICADOS

In [59]:

# Aplicar al DataFrame original
base_general_filtrada_pd["cau_cie10_std"] = base_general_filtrada_pd["cau_cie10"].map(mapping_final_dict)

print("Proceso completado. Columna 'cau_cie10_std' creada.")

Proceso completado. Columna 'cau_cie10_std' creada.

In [61]:
base_general_filtrada_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11172616 entries, 0 to 11172615
Data columns (total 42 columns):
 #   Column          Dtype
---  ------          -----
 0   prov_ubi        object
 1   cant_ubi        object
 2   parr_ubi        object
 3   area_ubi        object
 4   clase           object
 5   tipo            object
 6   entidad         object
 7   sector          object
 8   mes_inv         object
 9   nac_pac         object
 10  nom_pais        object
 11  cod_pais        object
 12  sexo            object
 13  cod_edad        object
 14  edad            object
 15  etnia           object
 16  prov_res        object
 17  cant_res        object
 18  parr_res        object
 19  area_res        object
 20  anio_ingr       object
 21  mes_ingr        object
 22  dia_ingr        object
 23  fecha_ingr      object
 24  anio_egr        object
 25  mes_egr         object
 26  dia_egr         object
 27  fecha_egr       object
 28  dia_estad       object
 29  con_egrpa       object
 30  esp_egrpa       object
 31  cau_cie10       object
 32  causa3          object
 33  cap221rx        object
 34  cau221rx        object
 35  cau298rx        object
 36  archivo_origen  object
 37  tipo_seg        object
 38  dis_pac         object
 39  edad_std        float64
 40  cau221rx_std    object
 41  cau_cie10_std   object
dtypes: float64(1), object(41)
memory usage: 3.5+ GB

In [62]:
base_general_filtrada_cie_10=pl.from_pandas(base_general_filtrada_pd)
del base_general_filtrada_pd
gc.collect()

245

### Resultados

In [63]:
base_general_filtrada=base_general_filtrada_cie_10.clone()
base_general_filtrada.select(pl.col("cau_cie10_std").is_null().sum())

shape: (1, 1)
┌───────────────┐
│ cau_cie10_std │
│ ---           │
│ u32           │
╞═══════════════╡
│ 0             │
└───────────────┘

In [65]:
# see wich cau221rx doesnt have a match in cau221rx_dict
cau_cie10_std_not_mapped=base_general_filtrada.filter(base_general_filtrada["cau_cie10_std"].is_null())

In [66]:
print(f"Códigos CIE-10 sin mapear: {cau_cie10_std_not_mapped['cau_cie10'].unique().to_list()}")

Códigos CIE-10 sin mapear: []

In [32]:
del base_general_filtrada_cie_10
gc.collect()

214

In [67]:
base_general_filtrada.describe()

shape: (9, 43)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ prov_ubi  ┆ cant_ubi ┆ parr_ubi  ┆ … ┆ dis_pac   ┆ edad_std  ┆ cau221rx_ ┆ cau_cie10 │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ std       ┆ _std      │
│ str       ┆ str       ┆ str      ┆ str       ┆   ┆ str       ┆ f64       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ str       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 11172616  ┆ 11172616 ┆ 11172616  ┆ … ┆ 1132667   ┆ 1.1172616 ┆ 11172616  ┆ 11172616  │
│           ┆           ┆          ┆           ┆   ┆           ┆ e7        ┆           ┆           │
│ null_coun ┆ 0         ┆ 0        ┆ 0         ┆ … ┆ 10039949  ┆ 0.0       ┆ 0         ┆ 0         │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 35.606243 ┆ null      ┆ null      │
│ std       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 23.804978 ┆ null      ┆ null      │
│ min       ┆ AZUAY     ┆ AGUARICO ┆ 10 DE     ┆ … ┆ Discapaci ┆ 0.000114  ┆ Afeccione ┆ A010      │
│           ┆           ┆          ┆ NOVIEMBRE ┆   ┆ dad       ┆           ┆ s         ┆ FIEBRE    │
│           ┆           ┆          ┆           ┆   ┆ auditiva  ┆           ┆ asociadas ┆ TIFOIDEA  │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ con la    ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ re…       ┆           │
│ 25%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 19.0      ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 31.0      ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null     ┆ null      ┆ … ┆ null      ┆ 53.0      ┆ null      ┆ null      │
│ max       ┆ ZAMORA    ┆ ZARUMA   ┆ ZUMBAHUA  ┆ … ┆ Sin infor ┆ 118.0     ┆ Urticaria ┆ ZINC Y    │
│           ┆ CHINCHIPE ┆          ┆           ┆   ┆ mación    ┆           ┆ y eritema ┆ SUS COMPU │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ (L50-L54) ┆ ESTOS     │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## MAPEO ubicacion

In [68]:
inec_parroquias=pd.read_csv("../../data/parroquias_cantones_inec.csv")

In [69]:
columns_to_strip_inec=["canton","parroquia","provincia"]
for column in columns_to_strip_inec:
    inec_parroquias[column] = inec_parroquias[column].str.strip()

In [70]:
inec_parroquias=inec_parroquias[["provincia","canton","parroquia","code_parroquia","sri_parroquia"]].drop_duplicates()

### Mapeo parroquias Hospitales

In [71]:

# --- 2. Función de Limpieza Extra ---
def clean_geo_text(text):
    if pd.isna(text): return ""
    text = str(text).upper()
   

    # Elimina todo lo que esté entre paréntesis: "ALAQUES (ALAQUEZ)" -> "ALAQUES"
    text=text.replace("(", "").replace(")", "")

    stop_words = [
        "DISTRITO METROPOLITANO DE", "D.M.", 
        "CABECERA CANTONAL", "PARROQUIA URBANA", 
        "PARROQUIA RURAL", "CENTRO POBLADO",
        "CANTON", "AREA URBANA", "PARROQUIA"
    ]
    for word in stop_words:
        text = text.replace(word, "")

    # Elimina caracteres especiales y deja solo letras y espacios
    text = re.sub(r'[^A-ZÁÉÍÓÚÑ\s]', '', text)
    return " ".join(text.split()) # Elimina espacios extra

# --- 3. Función de Fuzzy Match Mejorada ---
def find_best_location(row, reference_df, threshold=80,sufix="ubi"):
    prov_actual = row[f"prov_{sufix}"]
    candidates = reference_df[reference_df[f"prov_{sufix}"] == prov_actual].copy()
    
    if candidates.empty:
        return pd.Series([None, None], index=["code_parroquia", "sri_parroquia"])

    # Limpiamos el texto de entrada (el de tu base)
    # Comparamos Cantón + Parroquia limpios
    query_canton = clean_geo_text(row[f'cant_{sufix}'])
    query_parr = clean_geo_text(row[f'parr_{sufix}'])
    query = f"{query_canton} {query_parr}"
    
    # Preparamos la lista de opciones (limpias también)
    choices = (candidates[f"cant_{sufix}"].apply(clean_geo_text) + " " + 
            candidates[f"parr_{sufix}"].apply(clean_geo_text)).tolist()
    
    # Usamos token_set_ratio: es excelente para "ALAQUES" vs "ALAQUEZ" 
    # y maneja mucho mejor las diferencias ortográficas pequeñas.
    res = process.extractOne(
        query, 
        choices, 
        scorer=fuzz.token_set_ratio 
    )
    
    if res:
        match_str, score, idx = res
        if score >= threshold:
            matched_row = candidates.iloc[idx]
            return pd.Series([matched_row["code_parroquia"], matched_row["sri_parroquia"]], 
                            index=["code_parroquia", "sri_parroquia"])
    
    return pd.Series([None, None], index=["code_parroquia", "sri_parroquia"])

In [96]:

#
print("Iniciando Fuzzy Match de ubicaciones...")

# --- 2. Preparación de tu base ---
inec_parroquias_ubi =inec_parroquias.rename(columns={"provincia":"prov_ubi","canton":"cant_ubi","parroquia":"parr_ubi"})

base_general_filtrada_ubi=base_general_filtrada.select(territorio_ubi).unique()
print(f"Parroquias a matchear: {base_general_filtrada_ubi.shape[0]}")
base_general_filtrada_ubi_pd=base_general_filtrada_ubi.to_pandas()
for col in territorio_ubi:
    base_general_filtrada_ubi_pd[col] = base_general_filtrada_ubi_pd[col].str.strip().str.upper()


# 1. Limpiamos el catálogo del INEC antes del merge
catálogo_para_merge = (
    inec_parroquias_ubi
    .sort_values(by="sri_parroquia", ascending=False, na_position='last')
    .drop_duplicates(subset=["prov_ubi", "cant_ubi", "parr_ubi"], keep="first")
)


# A. Merge Exacto primero
base_final_ubi = base_general_filtrada_ubi_pd.merge(
    catálogo_para_merge[["prov_ubi", "cant_ubi", "parr_ubi","code_parroquia"]], 
    on=["prov_ubi", "cant_ubi", "parr_ubi"], 
    how="left"
)

mask_missing = base_final_ubi["code_parroquia"].isna()
print(f"Filas encontradas exactamente: {(~mask_missing).sum()}")
print(f"Filas para corregir con Fuzzy Match: {mask_missing.sum()}")

# B. Aplicar Fuzzy Match solo donde falló el exacto
if mask_missing.any():
    # El uso de result_type="expand" asegura que el resultado se asigne correctamente a las dos columnas
    fuzzy_results = base_final_ubi[mask_missing].apply(
        lambda r: find_best_location(r, catálogo_para_merge,sufix="ubi"), 
        axis=1
    )
    
    base_final_ubi.loc[mask_missing, ["code_parroquia"]] = fuzzy_results

# --- 5. Resultados ---
# Limpiar tipos de datos si es necesario (códigos a string/int)
base_final_ubi["code_parroquia"] = base_final_ubi["code_parroquia"].astype(str).replace("None", pd.NA)

# Mostrar algunas correcciones para validar
print("Mapeo de ubicación terminado.")
print(f"Filas totales: {base_final_ubi.shape[0]}")
print(f"Filas matcheadas: {base_final_ubi['code_parroquia'].notna().sum()}")
print(f"Códigos parroquia únicos encontrados: {base_final_ubi['code_parroquia'].nunique()}")

Iniciando Fuzzy Match de ubicaciones...
Parroquias a matchear: 412
Filas encontradas exactamente: 227
Filas para corregir con Fuzzy Match: 185
Mapeo de ubicación terminado.
Filas totales: 412
Filas matcheadas: 412
Códigos parroquia únicos encontrados: 357

### Mapeo Parroquias residencia

In [97]:

print("Iniciando Fuzzy Match de ubicaciones...")
inec_parroquias_res=inec_parroquias.rename(columns={"provincia":"prov_res","canton":"cant_res","parroquia":"parr_res"})

# 1. Limpiamos el catálogo del INEC antes del merge
catálogo_para_merge = (
    inec_parroquias_res
    .sort_values(by="sri_parroquia", ascending=False, na_position='last')
    .drop_duplicates(subset=["prov_res", "cant_res", "parr_res"], keep="first")
)


base_general_filtrada_res=base_general_filtrada.select(territorio_res).unique()
print(f"Parroquias a matchear: {base_general_filtrada_res.shape[0]}")
base_general_filtrada_res_pd=base_general_filtrada_res.to_pandas()
# --- 2. Preparación de tu base ---

for col in territorio_res:
    base_general_filtrada_res_pd[col] = base_general_filtrada_res_pd[col].str.strip().str.upper()


# --- 4. Ejecución del Proceso ---

# A. Merge Exacto primero
base_final_res = base_general_filtrada_res_pd.merge(
    catálogo_para_merge[["prov_res", "cant_res", "parr_res","code_parroquia"]], 
    on=["prov_res", "cant_res", "parr_res"], 
    how="left"
)

mask_missing = base_final_res["code_parroquia"].isna()
print(f"Filas encontradas exactamente: {(~mask_missing).sum()}")
print(f"Filas para corregir con Fuzzy Match: {mask_missing.sum()}")

# B. Aplicar Fuzzy Match solo donde falló el exacto
if mask_missing.any():
    # El uso de result_type="expand" asegura que el resultado se asigne correctamente a las dos columnas
    fuzzy_results = base_final_res[mask_missing].apply(
        lambda r: find_best_location(r, catálogo_para_merge,sufix="res"), 
        axis=1
    )
    
    base_final_res.loc[mask_missing, ["code_parroquia"]] = fuzzy_results

# --- 5. Resultados ---
# Limpiar tipos de datos si es necesario (códigos a string/int)
base_final_res["code_parroquia"] = base_final_res["code_parroquia"].astype(str).replace("None", pd.NA)

# Mostrar algunas correcciones para validar
print("Mapeo de ubicación terminado.")
print(f"Filas totales: {base_final_res.shape[0]}")
print(f"Filas matcheadas: {base_final_res['code_parroquia'].notna().sum()}")
#poner el numero de code parroquia unico
print(f"Códigos parroquia únicos encontrados: {base_final_res['code_parroquia'].nunique()}")

Iniciando Fuzzy Match de ubicaciones...
Parroquias a matchear: 1654
Filas encontradas exactamente: 1027
Filas para corregir con Fuzzy Match: 627
Mapeo de ubicación terminado.
Filas totales: 1654
Filas matcheadas: 1646
Códigos parroquia únicos encontrados: 1294

### Revision duplicados

In [102]:
# Ver qué combinaciones están repetidas en el catálogo del INEC
duplicados_inec = catálogo_para_merge[
    catálogo_para_merge.duplicated(subset=["prov_res", "cant_res", "parr_res"], keep=False)
]
print("Filas duplicadas en el catálogo INEC que causan la explosión:")
print(duplicados_inec)

Filas duplicadas en el catálogo INEC que causan la explosión:
Empty DataFrame
Columns: [prov_res, cant_res, parr_res, code_parroquia, sri_parroquia]
Index: []

In [103]:
# Para Residencia
base_final_res["key_text"] = (
    base_final_res["prov_res"].apply(clean_geo_text) + "_" + 
    base_final_res["cant_res"].apply(clean_geo_text) + "_" + 
    base_final_res["parr_res"].apply(clean_geo_text)
)

# Para Ubicación
base_final_ubi["key_text"] = (
    base_final_ubi["prov_ubi"].apply(clean_geo_text) + "_" + 
    base_final_ubi["cant_ubi"].apply(clean_geo_text) + "_" + 
    base_final_ubi["parr_ubi"].apply(clean_geo_text)
)

In [104]:
# El equivalente a is_duplicated() de Polars es duplicated(keep=False)
base_final_ubi_duplicates = base_final_ubi[base_final_ubi.duplicated(subset=["code_parroquia"], keep=False)]

base_final_res_duplicates = base_final_res[base_final_res.duplicated(subset=["code_parroquia"], keep=False)]

In [105]:
#review duplicados
print("Duplicados en base_final_ubi:")
print(base_final_ubi_duplicates[["prov_ubi","cant_ubi","parr_ubi","code_parroquia"]].sort_values("code_parroquia"))

Duplicados en base_final_ubi:
                           prov_ubi       cant_ubi  \
90                            AZUAY   SANTA ISABEL
278                           AZUAY   SANTA ISABEL
9                             CANAR        AZOGUES
160                           CANAR        AZOQUES
395                          CARCHI       MONTUFAR
..                              ...            ...
367  SANTO DOMINGO DE LOS TSACHILAS  SANTO DOMINGO
94                      SANTA ELENA    LA LIBERTAD
313                     SANTA ELENA    LA LIBERTAD
321                     SANTA ELENA        SALINAS
174                     SANTA ELENA        SALINAS

                                 parr_ubi code_parroquia
90             SANTA ISABEL (CHAGUARURCO)       EC010850
278       SANTA ISABEL, CABECERA CANTONAL       EC010850
9                                 AZOGUES       EC030102
160                               AZOGUES       EC030102
395        SAN GABRIEL, CABECERA CANTONAL       EC040550
..                                    ...            ...
367                               BAMBOLI       EC230102
94         LA LIBERTAD, CABECERA CANTONAL       EC240250
313                           LA LIBERTAD       EC240250
321  SALINAS, CABECERA, CABECERA CANTONAL       EC240350
174                    VICENTE ROCAFUERTE       EC240350

[110 rows x 4 columns]

In [106]:

print("\nDuplicados en base_final_res:")
print(base_final_res_duplicates[["prov_res","cant_res","parr_res","code_parroquia"]].sort_values("code_parroquia"))

Duplicados en base_final_res:
                  prov_res         cant_res          parr_res code_parroquia
428                  AZUAY           CUENCA        CHIQUINTAD       EC010155
1195                 AZUAY           CUENCA       CHUIQUINTAD       EC010155
1327                 AZUAY           CUENCA          SININCAY       EC010167
1445                 AZUAY           CUENCA           SINICAY       EC010167
187                  AZUAY           CUENCA            CUENCA       EC010171
...                    ...              ...               ...            ...
1014  ZONAS NO DELIMITADAS  LAS GOLONDRINAS   LAS GOLONDRINAS           <NA>
1183  ZONAS NO DELIMITADAS   MANGA DEL CURA    MANGA DEL CURA           <NA>
1203              EXTERIOR         EXTERIOR          EXTERIOR           <NA>
1536            ESMERALDAS         QUININDE  CHURA (CHANCAMA)           <NA>
1622  ZONAS NO DELIMITADAS      EL PIEDRERO       EL PIEDRERO           <NA>

[680 rows x 4 columns]

### Mapeo Shape file Parroquia

In [107]:

# --- FUNCIÓN FUZZY CORREGIDA ---
def find_best_conali_match(row, conali_df, threshold=80, sufix="res"):
    prov_actual = row[f"prov_{sufix}"]
    # Filtramos por prov_clean que ya está en el df
    candidates = conali_df[conali_df["prov_clean"] == clean_geo_text(prov_actual)].copy()
    
    if candidates.empty:
        return None

    query_canton = clean_geo_text(row[f'cant_{sufix}'])
    query_parr = clean_geo_text(row[f'parr_{sufix}'])
    query = f"{query_canton} {query_parr}"
    
    # Usamos las columnas ya limpias del shapefile
    choices = (candidates["cant_clean"] + " " + candidates["parr_clean"]).tolist()
    
    res = process.extractOne(query, choices, scorer=fuzz.token_set_ratio)
    
    if res:
        match_str, score, idx = res
        if score >= threshold:
            return candidates.index[idx]
    return None

In [108]:
import geopandas as gpd
cantones = gpd.read_file("../../data/organizacion-territorial-cantonal/ORGANIZACION_TERRITORIAL_CANTONAL.shp")
conali_parroquias_shape=gpd.read_file("../../data/LIMITE_PARROQUIAL_CONALI_CNE_2022/LIMITE_PARROQUIAL_CONALI_CNE_2022/LIMITE_PARROQUIAL_CONALI_CNE_2022.shp")

c:\Users\Kristian Mendoza\.conda\envs\rodri_msp_geo\Lib\site-packages\pyogrio\core.py:35: RuntimeWarning: Could not detect GDAL data files.  Set GDAL_DATA environment variable to the correct path.
  _init_gdal_data()

In [109]:
conali_parroquias=conali_parroquias_shape[["PROVINCIA", "CANTON","PARROQUIA","CODPAR"]]

In [110]:
conali_parroquias.columns

Index(['PROVINCIA', 'CANTON', 'PARROQUIA', 'CODPAR'], dtype='object')

In [111]:
# --- 1. PREPARACIÓN DE DICCIONARIO DE CÓDIGOS (std_parroquias) ---
# Limpiamos el código viejo para que coincida con el CODPAR del shapefile
std_parroquias = pd.read_csv("std_parroquias.csv")
std_parroquias["PARROQUIA_CODIGO_OLD"] = std_parroquias["PARROQUIA_CODIGO_OLD"].astype(str).str.replace(".0", "", regex=False).str.strip().str.zfill(4)
mapeo_old_to_new = dict(zip(std_parroquias["PARROQUIA_CODIGO_OLD"], std_parroquias["PARROQUIA_CODIGO"]))

conali_parroquias["code_parroquia"] = conali_parroquias["CODPAR"].astype(str).str.strip().map(mapeo_old_to_new)

C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\639192331.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conali_parroquias["code_parroquia"] = conali_parroquias["CODPAR"].astype(str).str.strip().map(mapeo_old_to_new)

In [ ]:
# Esto te mostrará qué códigos están repetidos en el shapefile
culpables_conali = conali_parroquias[conali_parroquias.duplicated(subset="code_parroquia", keep=False)]
print(culpables_conali.sort_values("code_parroquia"))

In [112]:
# Definir las columnas correctas del shapefile CONALI
# Según tu inspección: 'PROVINCIA', 'CANTON', 'PARROQUIA'
conali_parroquias["prov_clean"] = conali_parroquias["PROVINCIA"].apply(clean_geo_text)
conali_parroquias["cant_clean"] = conali_parroquias["CANTON"].apply(clean_geo_text)
conali_parroquias["parr_clean"] = conali_parroquias["PARROQUIA"].apply(clean_geo_text)

# Crear una llave única de texto para el join
conali_parroquias["key_text"] = (
    conali_parroquias["prov_clean"] + "_" + 
    conali_parroquias["cant_clean"] + "_" + 
    conali_parroquias["parr_clean"]
)

C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\2285053816.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conali_parroquias["prov_clean"] = conali_parroquias["PROVINCIA"].apply(clean_geo_text)
C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\2285053816.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conali_parroquias["cant_clean"] = conali_parroquias["CANTON"].apply(clean_geo_text)
C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\2285053816.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conali_parroquias["parr_clean"] = conali_parroquias["PARROQUIA"].apply(clean_geo_text)
C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\2285053816.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conali_parroquias["key_text"] = (

In [ ]:
# Paso 1: Intentar por Código INEC (Merge Exacto)
# Unimos tu base_final_res con el shapefile usando code_parroquia
print(f"Total de registros antes del merge: {len(base_final_res)}")
print("Intentando match por código INEC...")


# 1. Filtramos: Solo registros que TIENEN código y eliminamos duplicados de esos códigos
conali_para_codigo = (
    conali_parroquias
    .dropna(subset=["code_parroquia"]) # <--- CRUCIAL: Elimina los NaNs que causan la explosión
    .drop_duplicates(subset=["code_parroquia"])
)


base_geo_res = base_final_res.merge(
    conali_para_codigo[["code_parroquia", "CODPAR"]],
    left_on="code_parroquia",
    right_on="code_parroquia",
    how="left")
# Paso 2: Fallback por Texto Exacto
print(f"Registros sin geometría después del merge por código: {base_geo_res['CODPAR'].isna().sum()}")

mask_no_geo = base_geo_res["CODPAR"].isna()
if mask_no_geo.any():
    print(f"Paso 2: Intentando match por texto exacto para {mask_no_geo.sum()} filas...")
    base_geo_res.loc[mask_no_geo, "key_text"] = (
        base_geo_res.loc[mask_no_geo, "prov_res"].apply(clean_geo_text) + "_" +
        base_geo_res.loc[mask_no_geo, "cant_res"].apply(clean_geo_text) + "_" +
        base_geo_res.loc[mask_no_geo, "parr_res"].apply(clean_geo_text)
    )
    dict_geo_text = dict(zip(conali_parroquias["key_text"], conali_parroquias["CODPAR"]))
    base_geo_res.loc[mask_no_geo, "CODPAR"] = base_geo_res.loc[mask_no_geo, "key_text"].map(dict_geo_text)

# Paso 3: Fuzzy Match fallback
print(f"Registros sin geometría después del match por texto exacto: {base_geo_res['CODPAR'].isna().sum()}")

mask_missing = base_geo_res["CODPAR"].isna()
if mask_missing.any():
    print(f"Haciendo Fuzzy Match para {mask_missing.sum()} geometrías de residencia...")
    idx_matches = base_geo_res[mask_missing].apply(
        lambda r: find_best_conali_match(r, conali_parroquias, sufix="res"), axis=1
    )
    
    for row_idx, conali_idx in idx_matches.dropna().items():
        base_geo_res.at[row_idx, "CODPAR"] = conali_parroquias.at[conali_idx, "CODPAR"]


print(f"Total de registros: {len(base_geo_res)}")
print(f"Registros SIN geometría: {base_geo_res['CODPAR'].isna().sum()}")

print("Proceso terminado.")

Total de registros antes del merge: 1654
Intentando match por código INEC...
Registros sin geometría después del merge por código: 129
Paso 2: Intentando match por texto exacto para 129 filas...
Registros sin geometría después del match por texto exacto: 95
Haciendo Fuzzy Match para 95 geometrías de residencia...
Total de registros: 1654
Registros SIN geometría: 23
Proceso terminado.

In [120]:
# Paso 1: Intentar por Código INEC (Merge Exacto)
# Unimos tu base_final_res con el shapefile usando code_parroquia
print(f"Total de registros antes del merge: {len(base_final_ubi)}")
print("Intentando match por código INEC...")

# 1. Filtramos: Solo registros que TIENEN código y eliminamos duplicados de esos códigos
conali_para_codigo = (
    conali_parroquias
    .dropna(subset=["code_parroquia"]) # <--- CRUCIAL: Elimina los NaNs que causan la explosión
    .drop_duplicates(subset=["code_parroquia"])
)

base_geo_ubi = base_final_ubi.merge(
    conali_para_codigo[["code_parroquia", "CODPAR"]],
    left_on="code_parroquia",
    right_on="code_parroquia",
    how="left")
# Paso 2: Fallback por Texto Exacto
print(f"Registros sin geometría después del merge por código: {base_geo_ubi['CODPAR'].isna().sum()}")

mask_no_geo = base_geo_ubi["CODPAR"].isna()
if mask_no_geo.any():
    print(f"Paso 2: Intentando match por texto exacto para {mask_no_geo.sum()} filas...")
    base_geo_ubi.loc[mask_no_geo, "key_text"] = (
        base_geo_ubi.loc[mask_no_geo, "prov_ubi"].apply(clean_geo_text) + "_" +
        base_geo_ubi.loc[mask_no_geo, "cant_ubi"].apply(clean_geo_text) + "_" +
        base_geo_ubi.loc[mask_no_geo, "parr_ubi"].apply(clean_geo_text)
    )
    dict_geo_text = dict(zip(conali_parroquias["key_text"], conali_parroquias["CODPAR"]))
    base_geo_ubi.loc[mask_no_geo, "CODPAR"] = base_geo_ubi.loc[mask_no_geo, "key_text"].map(dict_geo_text)

# Paso 3: Fuzzy Match fallback
print(f"Registros sin geometría después del match por texto exacto: {base_geo_res['CODPAR'].isna().sum()}")

mask_missing = base_geo_ubi["CODPAR"].isna()
if mask_missing.any():
    print(f"Haciendo Fuzzy Match para {mask_missing.sum()} geometrías de residencia...")
    idx_matches = base_geo_ubi[mask_missing].apply(
        lambda r: find_best_conali_match(r, conali_parroquias, sufix="ubi"), axis=1
    )
    
    for row_idx, conali_idx in idx_matches.dropna().items():
        base_geo_ubi.at[row_idx, "CODPAR"] = conali_parroquias.at[conali_idx, "CODPAR"]

print(f"Total de registros: {len(base_geo_ubi)}")
print(f"Registros SIN geometría: {base_geo_ubi['CODPAR'].isna().sum()}")
print("Proceso terminado.")

Total de registros antes del merge: 412
Intentando match por código INEC...
Registros sin geometría después del merge por código: 73
Paso 2: Intentando match por texto exacto para 73 filas...
Registros sin geometría después del match por texto exacto: 23
Haciendo Fuzzy Match para 47 geometrías de residencia...
Total de registros: 412
Registros SIN geometría: 17
Proceso terminado.

In [121]:

# 4. Convertir a GeoDataFrame final y procesar coordenadas
#ver el de parroquias
print(conali_parroquias_shape.crs)
conali_parroquias_shape = conali_parroquias_shape.to_crs(epsg=4326)
print(conali_parroquias_shape.crs)
conali_parroquias_shape["centroid"] = conali_parroquias_shape.geometry.centroid
conali_parroquias_shape["lat_parroquia"] = conali_parroquias_shape.centroid.y
conali_parroquias_shape["lon_parroquia"] = conali_parroquias_shape.centroid.x

EPSG:4326
EPSG:4326

C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\2905253939.py:6: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  conali_parroquias_shape["centroid"] = conali_parroquias_shape.geometry.centroid
C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\2905253939.py:7: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  conali_parroquias_shape["lat_parroquia"] = conali_parroquias_shape.centroid.y
C:\Users\Kristian Mendoza\AppData\Local\Temp\ipykernel_26936\2905253939.py:8: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  conali_parroquias_shape["lon_parroquia"] = conali_parroquias_shape.centroid.x

In [122]:
base_geo_res=base_geo_res.merge(conali_parroquias_shape[["CODPAR","lat_parroquia","lon_parroquia"]], on="CODPAR", how="left").rename(columns={"lat_parroquia":"lat_res","lon_parroquia":"lon_res"}).drop(columns=["CODPAR"])
base_geo_ubi=base_geo_ubi.merge(conali_parroquias_shape[["CODPAR","lat_parroquia","lon_parroquia"]], on="CODPAR", how="left").rename(columns={"lat_parroquia":"lat_ubi","lon_parroquia":"lon_ubi"}).drop(columns=["CODPAR"])

In [123]:
base_geo_res_pl=pl.from_pandas(base_geo_res)
base_geo_ubi_pl=pl.from_pandas(base_geo_ubi)
del base_geo_res
del base_geo_ubi

In [124]:

base_general_filtrada=base_general_filtrada.join(base_geo_res_pl,on=["prov_res","cant_res","parr_res"],how="left")
base_general_filtrada=base_general_filtrada.join(base_geo_ubi_pl,on=["prov_ubi","cant_ubi","parr_ubi"],how="left")

In [125]:
print(base_general_filtrada.select(pl.col("lat_ubi","lat_res").is_null().sum()))

shape: (1, 2)
┌─────────┬─────────┐
│ lat_ubi ┆ lat_res │
│ ---     ┆ ---     │
│ u32     ┆ u32     │
╞═════════╪═════════╡
│ 1065957 ┆ 557214  │
└─────────┴─────────┘

In [126]:
# review from parr_ubi and parr_res cuantos son los que tienen más null en lat_ubi and lat_res
# Filtrar las filas donde 'lat_res' es nulo y mostrar el valor de 'parr_res'

# Filtrar las filas donde 'lat_res' es nulo y luego agrupar por 'parr_res'
result_res = base_general_filtrada.filter(pl.col("lat_res").is_null()) \
    .group_by("prov_res","cant_res","parr_res") \
    .agg(pl.len().alias("null_count"))\
    .sort("null_count",descending=True)

# Mostrar el resultado
print(result_res)

shape: (23, 4)
┌────────────────────────────────┬─────────────────┬─────────────────────────────────┬────────────┐
│ prov_res                       ┆ cant_res        ┆ parr_res                        ┆ null_count │
│ ---                            ┆ ---             ┆ ---                             ┆ ---        │
│ str                            ┆ str             ┆ str                             ┆ u32        │
╞════════════════════════════════╪═════════════════╪═════════════════════════════════╪════════════╡
│ PICHINCHA                      ┆ QUITO           ┆ QUITO , CABECERA CANTONAL Y CA… ┆ 189098     │
│ GUAYAS                         ┆ GUAYAQUIL       ┆ GUAYAQUIL , CABECERA CANTONAL … ┆ 106027     │
│ IMBABURA                       ┆ IBARRA          ┆ SAN MIGUEL DE IBARRA            ┆ 58000      │
│ AZUAY                          ┆ CUENCA          ┆ CUENCA , CABECERA CANTONAL Y C… ┆ 55507      │
│ SANTO DOMINGO DE LOS TSACHILAS ┆ SANTO DOMINGO   ┆ SANTO DOMINGO DE LOS COLORADOS… ┆ 33321      │
│ …                              ┆ …               ┆ …                               ┆ …          │
│ LOS RIOS                       ┆ BUENA FE        ┆ 7 DE AGOSTO                     ┆ 230        │
│ EL ORO                         ┆ LAS LAJAS       ┆ VALLE HERMOSO                   ┆ 135        │
│ ZONAS NO DELIMITADAS           ┆ MANGA DEL CURA  ┆ MANGA DEL CURA                  ┆ 128        │
│ ZONAS NO DELIMITADAS           ┆ LAS GOLONDRINAS ┆ LAS GOLONDRINAS                 ┆ 86         │
│ ZONAS NO DELIMITADAS           ┆ EL PIEDRERO     ┆ EL PIEDRERO                     ┆ 59         │
└────────────────────────────────┴─────────────────┴─────────────────────────────────┴────────────┘

In [127]:
# Filtrar las filas donde 'lat_res' es nulo y luego agrupar por 'parr_res'
result_ubi = base_general_filtrada.filter(pl.col("lat_ubi").is_null()) \
    .group_by("prov_ubi","cant_ubi","parr_ubi") \
    .agg(pl.len().alias("null_count")) \
    .sort("null_count",descending=True)
# Mostrar el resultado
print(result_ubi)

shape: (17, 4)
┌────────────┬───────────┬─────────────────────────────────┬────────────┐
│ prov_ubi   ┆ cant_ubi  ┆ parr_ubi                        ┆ null_count │
│ ---        ┆ ---       ┆ ---                             ┆ ---        │
│ str        ┆ str       ┆ str                             ┆ u32        │
╞════════════╪═══════════╪═════════════════════════════════╪════════════╡
│ GUAYAS     ┆ GUAYAQUIL ┆ GUAYAQUIL , CABECERA CANTONAL … ┆ 331406     │
│ PICHINCHA  ┆ QUITO     ┆ QUITO , CABECERA CANTONAL Y CA… ┆ 248060     │
│ AZUAY      ┆ CUENCA    ┆ CUENCA , CABECERA CANTONAL Y C… ┆ 104836     │
│ IMBABURA   ┆ IBARRA    ┆ SAN MIGUEL DE IBARRA            ┆ 82898      │
│ LOJA       ┆ LOJA      ┆ LOJA , CABECERA CANTONAL Y CAP… ┆ 56453      │
│ …          ┆ …         ┆ …                               ┆ …          │
│ BOLIVAR    ┆ GUARANDA  ┆ GUARANDA, CABECERA CANTONAL Y … ┆ 14649      │
│ IMBABURA   ┆ COTACAHI  ┆ COTACACHI                       ┆ 9343       │
│ CHIMBORAZO ┆ COLTA     ┆ VILLA LA UNION, CABECERA CANTO… ┆ 1913       │
│ LOS RIOS   ┆ BUENA FE  ┆ 7 DE AGOSTO                     ┆ 717        │
│ LOS RIOS   ┆ BUENA FE  ┆ 11 DE OCTUBRE                   ┆ 329        │
└────────────┴───────────┴─────────────────────────────────┴────────────┘

In [128]:


base_general_filtrada=base_general_filtrada.drop(["key_text_right","key_text"])

In [129]:
# quitar las columnas key_text, key_text_right. renombrar code_parroquia a code_parroquia_res y code_parroquia_right a code_parroquia_ubi
base_general_filtrada=base_general_filtrada.with_columns([
        pl.col("code_parroquia").alias("code_parr_res"),
        pl.col("code_parroquia_right").alias("code_parr_ubi")
    ])

In [130]:

#base_general_filtrada=base_general_filtrada.drop(["cau221rx","cau_cie10"])
base_general_filtrada=base_general_filtrada.drop(["code_parroquia_right","code_parroquia"])

In [131]:
base_general_filtrada.describe()

shape: (9, 49)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ prov_ubi  ┆ cant_ubi ┆ parr_ubi  ┆ … ┆ lat_ubi   ┆ lon_ubi   ┆ code_parr ┆ code_parr │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ _res      ┆ _ubi      │
│ str       ┆ str       ┆ str      ┆ str       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ str       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 11172616  ┆ 11172616 ┆ 11172616  ┆ … ┆ 1.0106659 ┆ 1.0106659 ┆ 11159840  ┆ 11172616  │
│           ┆           ┆          ┆           ┆   ┆ e7        ┆ e7        ┆           ┆           │
│ null_coun ┆ 0         ┆ 0        ┆ 0         ┆ … ┆ 1.065957e ┆ 1.065957e ┆ 12776     ┆ 0         │
│ t         ┆           ┆          ┆           ┆   ┆ 6         ┆ 6         ┆           ┆           │
│ mean      ┆ null      ┆ null     ┆ null      ┆ … ┆ -1.469359 ┆ -79.26588 ┆ null      ┆ null      │
│ std       ┆ null      ┆ null     ┆ null      ┆ … ┆ 1.21206   ┆ 0.94323   ┆ null      ┆ null      │
│ min       ┆ AZUAY     ┆ AGUARICO ┆ 10 DE     ┆ … ┆ -4.85071  ┆ -90.31730 ┆ EC010101  ┆ EC010101  │
│           ┆           ┆          ┆ NOVIEMBRE ┆   ┆           ┆ 7         ┆           ┆           │
│ 25%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -2.28079  ┆ -79.92952 ┆ null      ┆ null      │
│ 50%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -1.47221  ┆ -79.18235 ┆ null      ┆ null      │
│ 75%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -0.242247 ┆ -78.53845 ┆ null      ┆ null      │
│           ┆           ┆          ┆           ┆   ┆           ┆ 9         ┆           ┆           │
│ max       ┆ ZAMORA    ┆ ZARUMA   ┆ ZUMBAHUA  ┆ … ┆ 1.276242  ┆ -75.57063 ┆ EC240352  ┆ EC240352  │
│           ┆ CHINCHIPE ┆          ┆           ┆   ┆           ┆ 3         ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [132]:
# posiblemente tenga algunos duplicados pero no sé como identificarlos
# Encuentra las filas duplicadas
df_duplicates = base_general_filtrada.filter(base_general_filtrada.is_duplicated())

In [133]:
# Verificar duplicados solo en ciertas columnas
#df_duplicates = base_general_filtrada.filter(base_general_filtrada.select(["clase","tipo","entidad","sector","prov_ubi","cant_ubi","parr_ubi","prov_res","cant_res","parr_res","fecha_egr","dia_estad","con_egrpa","causa3","cap221rx","cau298rx","edad_std","cau_cie10_std","cau221rx_std","code_parr_res","code_parr_ubi"]).is_duplicated())
print(df_duplicates.shape)

(58889, 48)

In [134]:
df_duplicates.describe()

shape: (9, 49)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ prov_ubi  ┆ cant_ubi ┆ parr_ubi  ┆ … ┆ lat_ubi   ┆ lon_ubi   ┆ code_parr ┆ code_parr │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ _res      ┆ _ubi      │
│ str       ┆ str       ┆ str      ┆ str       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ str       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 58889     ┆ 58889    ┆ 58889     ┆ … ┆ 51186.0   ┆ 51186.0   ┆ 58883     ┆ 58889     │
│ null_coun ┆ 0         ┆ 0        ┆ 0         ┆ … ┆ 7703.0    ┆ 7703.0    ┆ 6         ┆ 0         │
│ t         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null     ┆ null      ┆ … ┆ -1.71552  ┆ -79.61633 ┆ null      ┆ null      │
│ std       ┆ null      ┆ null     ┆ null      ┆ … ┆ 0.966079  ┆ 0.791427  ┆ null      ┆ null      │
│ min       ┆ AZUAY     ┆ AGUARICO ┆ 10 DE     ┆ … ┆ -4.85071  ┆ -90.31730 ┆ EC010101  ┆ EC010101  │
│           ┆           ┆          ┆ NOVIEMBRE ┆   ┆           ┆ 7         ┆           ┆           │
│ 25%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -2.252261 ┆ -79.97962 ┆ null      ┆ null      │
│           ┆           ┆          ┆           ┆   ┆           ┆ 8         ┆           ┆           │
│ 50%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -2.212544 ┆ -79.89720 ┆ null      ┆ null      │
│           ┆           ┆          ┆           ┆   ┆           ┆ 4         ┆           ┆           │
│ 75%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -1.024344 ┆ -79.23679 ┆ null      ┆ null      │
│           ┆           ┆          ┆           ┆   ┆           ┆ 5         ┆           ┆           │
│ max       ┆ ZAMORA    ┆ ZARUMA   ┆ ZUMBAHUA  ┆ … ┆ 1.276242  ┆ -75.57063 ┆ EC240352  ┆ EC240352  │
│           ┆ CHINCHIPE ┆          ┆           ┆   ┆           ┆ 3         ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
# Eliminar duplicados
base_general_filtrada_no_dups = base_general_filtrada.unique()  # Esto mantendrá solo las primeras ocurrencias y elimina las duplicadas
print(base_general_filtrada_no_dups.shape)

(11142010, 48)

In [136]:

del base_general_filtrada_no_dups
gc.collect()

120

# Extraer cie 10 especificos

Obesidad E66 (E66.0, E66.01, E66.09, E66.8, E66.9, E66.3, E66.81, E66.811, E66.812, E66.813)

Hipertrigliceridemia: E78, E78.1, E78.3, E78.5, E78.5, E78.6
* Causes

* Diabetes (E10-E14, O24)

gen diabetes = 0
replace diabetes = 1 if causeICD10 == "E11"

* Hypertensive (I10-I15)

gen hyper = 0
replace hyper = 1 if causeICD10 == "I10"

* Myocardial infarction (I21-I22)

gen infarction = 0
replace infarction = 1 if (causeICD10 == "I21" | causeICD10 == "I22")

Esto sí es. Aquí tienes en código de stata lo que estamos usando. En resumen, E11, I10 y I21,I22

In [139]:
import polars as pl

# 1. Definimos las condiciones como expresiones de Polars
# Usamos (?i) al inicio del regex para que sea case-insensitive (equivalente a case=False)

# Diabetes
cond_diabetes = (
    pl.col("cau_cie10_std").str.contains(r"E1[0-4]|O24") 
    #pl.col("cau_cie10_std").str.contains(r"(?i)DIABETES") |
    #pl.col("cau221rx_std").str.contains(r"(?i)DIABETES")
)

# Obesidad
cond_obesity = (
    pl.col("cau_cie10_std").str.contains(r"E66") |
    pl.col("cau_cie10_std").str.contains(r"(?i)OBES")# |
    #pl.col("cau221rx_std").str.contains(r"(?i)OBES")
)

# Hipertensión (aquí text_enabled era False en tu código)
cond_hyper = pl.col("cau_cie10_std").str.contains(r"I1[0-5]")

# Infartos
cond_infarction = (
    pl.col("cau_cie10_std").str.contains(r"I21|I22") 
    #pl.col("cau_cie10_std").str.contains(r"(?i)INFARTO") |
    #pl.col("cau221rx_std").str.contains(r"(?i)INFARTO")
)

# Hipertrigliceridemia
cond_hiper_trig = (
    pl.col("cau_cie10_std").str.contains(r"E78") #|
    # pl.col("cau_cie10_std").str.contains(r"(?i)HIPERTRI") |
    # pl.col("cau221rx_std").str.contains(r"(?i)HIPERTRI")
)

# 2. Aplicamos todo al DataFrame
base_general_filtrada = base_general_filtrada.with_columns(
    sindrome_metabolico = pl.when(
        cond_diabetes | cond_obesity | cond_hyper | cond_infarction | cond_hiper_trig
    )
    .then(1)
    .otherwise(0)
    .cast(pl.Int8) # Opcional: para que ocupe menos memoria que un Int64
)

# Para ver cuántos casos positivos tienes:
print(base_general_filtrada["sindrome_metabolico"].value_counts())

shape: (2, 2)
┌─────────────────────┬──────────┐
│ sindrome_metabolico ┆ count    │
│ ---                 ┆ ---      │
│ i8                  ┆ u32      │
╞═════════════════════╪══════════╡
│ 1                   ┆ 298524   │
│ 0                   ┆ 10874092 │
└─────────────────────┴──────────┘

In [140]:
resumen_cie10 = (
    base_general_filtrada_no_dups
    .filter(pl.col("sindrome_metabolico") == 1)
    .group_by("cau_cie10_std") # Agrupamos por el código
    .len()                     # Contamos (en versiones viejas usa .count())
    .sort("len", descending=True) # Ordenamos de mayor a menor
)

In [141]:
display(resumen_cie10)

shape: (118, 2)
┌─────────────────────────────────┬───────┐
│ cau_cie10_std                   ┆ len   │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ I10   HIPERTENSION ESENCIAL (P… ┆ 48810 │
│ I219   INFARTO AGUDO DEL MIOCA… ┆ 27350 │
│ E119 DIABETES MELLITUS NO INSU… ┆ 24900 │
│ E669   OBESIDAD, NO ESPECIFICA… ┆ 18225 │
│ E119   DIABETES MELLITUS TIPO … ┆ 14727 │
│ …                               ┆ …     │
│ E14 DIABETES MELLITUS, NO ESPE… ┆ 13    │
│ E133   OTRAS DIABETES MELLITUS… ┆ 8     │
│ E783   HIPERQUILOMICRONEMIA     ┆ 8     │
│ E661   OBESIDAD INDUCIDA POR D… ┆ 6     │
│ E123 DIABETES MELLITUS ASOCIAD… ┆ 4     │
└─────────────────────────────────┴───────┘

## Diferentes outputs

## la base con todo en stata

In [143]:
import pyreadstat

In [144]:
base_general_filtrada.describe()

shape: (9, 50)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ prov_ubi  ┆ cant_ubi ┆ parr_ubi  ┆ … ┆ lon_ubi   ┆ code_parr ┆ code_parr ┆ sindrome_ │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ ---       ┆ _res      ┆ _ubi      ┆ metabolic │
│ str       ┆ str       ┆ str      ┆ str       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ o         │
│           ┆           ┆          ┆           ┆   ┆           ┆ str       ┆ str       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 11172616  ┆ 11172616 ┆ 11172616  ┆ … ┆ 1.0106659 ┆ 11159840  ┆ 11172616  ┆ 1.1172616 │
│           ┆           ┆          ┆           ┆   ┆ e7        ┆           ┆           ┆ e7        │
│ null_coun ┆ 0         ┆ 0        ┆ 0         ┆ … ┆ 1.065957e ┆ 12776     ┆ 0         ┆ 0.0       │
│ t         ┆           ┆          ┆           ┆   ┆ 6         ┆           ┆           ┆           │
│ mean      ┆ null      ┆ null     ┆ null      ┆ … ┆ -79.26588 ┆ null      ┆ null      ┆ 0.026719  │
│ std       ┆ null      ┆ null     ┆ null      ┆ … ┆ 0.94323   ┆ null      ┆ null      ┆ 0.161262  │
│ min       ┆ AZUAY     ┆ AGUARICO ┆ 10 DE     ┆ … ┆ -90.31730 ┆ EC010101  ┆ EC010101  ┆ 0.0       │
│           ┆           ┆          ┆ NOVIEMBRE ┆   ┆ 7         ┆           ┆           ┆           │
│ 25%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -79.92952 ┆ null      ┆ null      ┆ 0.0       │
│ 50%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -79.18235 ┆ null      ┆ null      ┆ 0.0       │
│ 75%       ┆ null      ┆ null     ┆ null      ┆ … ┆ -78.53845 ┆ null      ┆ null      ┆ 0.0       │
│           ┆           ┆          ┆           ┆   ┆ 9         ┆           ┆           ┆           │
│ max       ┆ ZAMORA    ┆ ZARUMA   ┆ ZUMBAHUA  ┆ … ┆ -75.57063 ┆ EC240352  ┆ EC240352  ┆ 1.0       │
│           ┆ CHINCHIPE ┆          ┆           ┆   ┆ 3         ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [145]:
# 2. Define the output file path
output_path = "../../data/data_hospitales/sistema_salud_egresos_limpio.dta"

# 3. Write the Polars DataFrame to a Stata .dta file
# The write_dta function from pyreadstat handles the conversion internally.
pyreadstat.write_dta(base_general_filtrada_no_dups, output_path)

Con edad

In [ ]:
# 1. Aseguramos que las listas de columnas estén presentes para evitar errores
# (Ya las definiste arriba, pero las incluimos en la lógica del group_by)

# 2. Agrupamiento y Conteo
base_general_filtrada_for_group=base_general_filtrada.clone()
DATE_FORMAT = "%Y-%m-%d"
#2. Agrupamiento con conversión de fecha integrada
resumen_egresos = (
    base_general_filtrada_for_group
    .with_columns([
        # Convertimos texto a fecha antes de extraer año/mes
        pl.col("fecha_egr").str.to_date(DATE_FORMAT)
    ])
    .with_columns([
        pl.col("fecha_egr").dt.year().alias("anio_egr"),
        pl.col("fecha_egr").dt.month().alias("mes_egr")
    ])
    .group_by([
        "anio_egr", 
        "mes_egr",
        *identificadores,    # ['clase', 'tipo', 'entidad', 'sector']
        *territorio_ubi,     # ['prov_ubi', 'cant_ubi', 'parr_ubi']
        "cau221rx_std",
        "con_egrpa",
        "edad_std"          # Diagnóstico final
    ])
    .agg([
        pl.len().alias("total_egresos"),
    ])

)

# 3. Verificación de los resultados
print("Estructura del resumen agrupado:")
print(resumen_egresos.head())

Estructura del resumen agrupado:
shape: (5, 13)
┌──────────┬─────────┬────────────┬────────────┬───┬────────────┬───────────┬──────────┬───────────┐
│ anio_egr ┆ mes_egr ┆ clase      ┆ tipo       ┆ … ┆ cau221rx_s ┆ con_egrpa ┆ edad_std ┆ total_egr │
│ ---      ┆ ---     ┆ ---        ┆ ---        ┆   ┆ td         ┆ ---       ┆ ---      ┆ esos      │
│ i32      ┆ i8      ┆ str        ┆ str        ┆   ┆ ---        ┆ str       ┆ f64      ┆ ---       │
│          ┆         ┆            ┆            ┆   ┆ str        ┆           ┆          ┆ u32       │
╞══════════╪═════════╪════════════╪════════════╪═══╪════════════╪═══════════╪══════════╪═══════════╡
│ 2019     ┆ 12      ┆ HOSPITAL   ┆ Agudo      ┆ … ┆ Trastornos ┆ Fallecido ┆ 80.0     ┆ 1         │
│          ┆         ┆ GENERAL    ┆            ┆   ┆ metabólico ┆ en 48     ┆          ┆           │
│          ┆         ┆            ┆            ┆   ┆ s (E70-E9… ┆ horas y   ┆          ┆           │
│          ┆         ┆            ┆            ┆   ┆            ┆ más       ┆          ┆           │
│ 2023     ┆ 7       ┆ HOSPITAL   ┆ Agudo      ┆ … ┆ Traumatism ┆ Vivo      ┆ 48.0     ┆ 1         │
│          ┆         ┆ DE ESPECIA ┆            ┆   ┆ os de la   ┆           ┆          ┆           │
│          ┆         ┆ LIDADES    ┆            ┆   ┆ rodilla y  ┆           ┆          ┆           │
│          ┆         ┆            ┆            ┆   ┆ l…         ┆           ┆          ┆           │
│ 2021     ┆ 10      ┆ HOSPITAL   ┆ Agudo      ┆ … ┆ Traumatism ┆ Vivo      ┆ 61.0     ┆ 1         │
│          ┆         ┆ GENERAL    ┆            ┆   ┆ os de la   ┆           ┆          ┆           │
│          ┆         ┆            ┆            ┆   ┆ cabeza     ┆           ┆          ┆           │
│          ┆         ┆            ┆            ┆   ┆ (S00…      ┆           ┆          ┆           │
│ 2020     ┆ 11      ┆ CLINICA    ┆ Clínicas   ┆ … ┆ Otras enfe ┆ Vivo      ┆ 64.0     ┆ 1         │
│          ┆         ┆ GENERAL    ┆ generales  ┆   ┆ rmedades   ┆           ┆          ┆           │
│          ┆         ┆ (SIN       ┆ sin        ┆   ┆ del        ┆           ┆          ┆           │
│          ┆         ┆ ESPECIALI… ┆ especia…   ┆   ┆ sistema…   ┆           ┆          ┆           │
│ 2024     ┆ 11      ┆ HOSPITAL   ┆ Agudo      ┆ … ┆ Enfermedad ┆ Vivo      ┆ 42.0     ┆ 1         │
│          ┆         ┆ DE ESPECIA ┆            ┆   ┆ es del     ┆           ┆          ┆           │
│          ┆         ┆ LIDADES    ┆            ┆   ┆ apéndice   ┆           ┆          ┆           │
│          ┆         ┆            ┆            ┆   ┆ (K35…      ┆           ┆          ┆           │
└──────────┴─────────┴────────────┴────────────┴───┴────────────┴───────────┴──────────┴───────────┘

In [ ]:
resumen_egresos.write_csv("../../data/processed/resumen_egresos_v3.csv")